name: KarasuLab Mod Releaser

on:
  push:
    branches:
      - main

jobs:
  call-release:
    uses: ./.github/workflows/release/release-please.yml
    with:
      modrinth_project_id: ${{ vars.MODRINTH_PROJECT_ID }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge_project_id: ${{ vars.CURSEFORGE_PROJECT_ID }}
      curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
    secrets: inherit
